### ISSUE TITLE
NavigationEventListener not working

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#386]
It seems in navigations current state, NavigationEventListener has been broken and isn't invoking the callback when navigation starts/ends.

cc: @zugaldia @Guardiola31337

**Comment by KatieBarnett** [comment]
I can't seem to get AlertLevelChangeListener and ProgressChangeListener working either.(OffRouteListener is listed as not yet implemented in the documentation so that is expected)
Followed the documentation here: https://www.mapbox.com/mapbox-java/#listeners with MAS v2.0.0-beta.3

**Comment by cammace** [comment]
This is the correct documentation location for navigation but hasn't been updated since making a few api breaking changes. Are you starting the navigation session? Any code or log output to troubleshoot the issue would help! Thanks for trying out navigation in it's early stage :)

**Comment by KatieBarnett** [comment]
Thanks for getting back to me. I'm trying to match functionality with an iOS a colleague is developing so I have been following the betas closely.

If it helps I have also found that the getLastLocation function often returns null and seems slow to register a location change. I can provide the code I am using there as well.

Not much in the logs, I saw the following:
```
I/SensorManager: unregisterListenerImpl++: listener = com.mapbox.mapboxsdk.maps.widgets.MyLocationView$CompassListener@99f4db9
```

Here is what I am doing to kick off the navigation (bits and pieces here, I have tried to remove the non essential code)

Location initialisation:
```java
        locationManager = (LocationManager) this.getSystemService(Context.LOCATION_SERVICE);
        locationService = LocationSource.getLocationEngine(this);
        locationService.activate();
```
Starting navigation:
```java
               // Origin is always the current location
                    Position originPos = Position.fromCoordinates(currentLocation.getLongitude(), currentLocation.getLatitude());
                    Position destinationPos = Position.fromCoordinates(tourDestination.longitude, tourDestination.latitude);

                    // Update polyline
                    if (map.getPolylines().size() > 0) {
                        Polyline existingRouteLine = map.getPolylines().get(0);
                        map.removePolyline(existingRouteLine);
                    }

                    ArrayList<Position> positionWaypoints = new ArrayList<>();
                    positionWaypoints.add(originPos);
                    for (WaypointItem waypoint : navigationWaypoints) {
                        positionWaypoints.add(Position.fromCoordinates(waypoint.longitude, waypoint.latitude));
                    }

                    getRoute(originPos, destinationPos, positionWaypoints);

                    navigationService = new MapboxNavigation(this, Mapbox.getAccessToken());
                    navigationService.setLocationEngine(locationService);
                    navigationService.setNavigationEventListener(this);
                    navigationService.setOffRouteListener(this);
                    navigationService.setAlertLevelChangeListener(this);
                    navigationService.setProgressChangeListener(this);
                    navigationService.setOrigin(originPos);
                    // Get the first navigation waypoint as the destination
                    Position nextWaypointPos = Position.fromCoordinates(navigationWaypoints.get(0).longitude, navigationWaypoints.get(0).latitude);
                    navigationService.setDestination(nextWaypointPos);
                    navigationService.getRoute(new Callback<DirectionsResponse>() {
                        @Override
                        public void onResponse(
                                Call<DirectionsResponse> call, Response<DirectionsResponse> response) {
                            // Do nothing, assume this worked
                        }

                        @Override
                        public void onFailure(Call<DirectionsResponse> call, Throwable t) {
                            MapNavigationDialog dialog = new MapNavigationDialog();
                            Bundle bundle = new Bundle();
                            bundle.putString(MapNavigationDialog.EXTRA_MSG, getString(R.string.dialog_map_navigation_error_text));
                            dialog.setArguments(bundle);
                            dialog.show(getFragmentManager(), MapNavigationDialog.DIALOG_TAG);
                        }
                    });
```

getRoute function is just to draw the route, but in case it is impacting the navigation here it is:
```java
private void getRoute(Position origin, Position destination, ArrayList<Position> waypoints) throws ServicesException {

        MapboxDirections client = new MapboxDirections.Builder()
                .setOrigin(origin)
                .setDestination(destination)
                .setCoordinates(waypoints)
                .setProfile(DirectionsCriteria.PROFILE_DRIVING)
                .setSteps(true)
                .setAccessToken(Mapbox.getAccessToken())
                .build();

        client.enqueueCall(new Callback<DirectionsResponse>() {
            @Override
            public void onResponse(Call<DirectionsResponse> call, Response<DirectionsResponse> response) {
                // You can get the generic HTTP info about the response
                Log.d(TAG, "Response code: " + response.code());
                if (response.body() == null) {
                    Log.e(TAG, "No routes found, make sure you set the right user and access token.");
                    return;
                } else if (response.body().getRoutes().size() < 1) {
                    Log.e(TAG, "No routes found");
                    return;
                }
                currentRoute = response.body().getRoutes().get(0);
                drawRoute(currentRoute);
            }

            @Override
            public void onFailure(Call<DirectionsResponse> call, Throwable throwable) {
                Log.e(TAG, "Error: " + throwable.getMessage());
                Toast.makeText(TourActivity.this, "Error: " + throwable.getMessage(), Toast.LENGTH_SHORT).show();
            }
        });
    }
```

Listeners, basically what the documentation has (I'm breakpointing on these to see if they are called)

```java
    @Override
    public void onRunning(boolean running) {
        Log.d(TAG, "RUNNING");

    }

    @Override
    public void userOffRoute(Location location) {
        // TODO not yet implemented in SDK

        Log.d(TAG, "OFF ROUTE");
    }

    @Override
    public void onAlertLevelChange(int alertLevel, RouteProgress routeProgress) {
        switch (alertLevel) {
            case com.mapbox.services.android.Constants.HIGH_ALERT_LEVEL:
                Toast.makeText(this, "HIGH", Toast.LENGTH_LONG).show();
                break;
            case com.mapbox.services.android.Constants.MEDIUM_ALERT_LEVEL:
                Toast.makeText(this, "MEDIUM", Toast.LENGTH_LONG).show();
                break;
            case com.mapbox.services.android.Constants.LOW_ALERT_LEVEL:
                Toast.makeText(this, "LOW", Toast.LENGTH_LONG).show();
                break;
            case com.mapbox.services.android.Constants.ARRIVE_ALERT_LEVEL:
                Toast.makeText(this, "ARRIVE", Toast.LENGTH_LONG).show();
                break;
            case com.mapbox.services.android.Constants.NONE_ALERT_LEVEL:
                Toast.makeText(this, "NONE", Toast.LENGTH_LONG).show();
                break;
            case com.mapbox.services.android.Constants.DEPART_ALERT_LEVEL:
                Toast.makeText(this, "DEPART", Toast.LENGTH_LONG).show();

                showNextStop();
                break;
        }
    }

    @Override
    public void onProgressChange(Location location, RouteProgress routeProgress) {

        TextView tourDistance = (TextView) findViewById(R.id.tour_destination_distance);
        tourDistance.setText(MapUtil.getDistanceString(TourActivity.this, prefs, routeProgress.getDistanceRemainingOnRoute()));
    }
```

**Comment by cammace** [comment]
Thanks for all the code snippets, really helps when troubleshooting. A few notes that might make things easier:

- There's no need to build your own directions call since `NavigationService.getRoute()` does this. Just handle drawing the route inside the callbacks response and remove your `getRoute` method. 

- You might want set your location engines priority to a higher state. We just added a fix to the LOST location engine that should help increase the amount of updates you receive https://github.com/mapbox/mapbox-java/pull/393.

**Comment by KatieBarnett** [comment]
Thanks for that. I'll make those changes.

I have updated to the released versions of MAS and the Android SDK and I am still not getting updates from those callbacks.

**Comment by KatieBarnett** [comment]
It seems I was missing the call to actually start the navigation (which wasn't in any of the (preview) documentation:

`navigationService.startNavigation(currentRoute);`

I have now included it in the `getRoute` `onResponse` callback and the `onProgressChange` method is now called. Unfortunately it appears the `RouteProgress` object is not quite right, the `distanceRemainingOnStep` value is changing, `distanceRemainingOnRoute` is not changing (despite the location marker moving and the location object in `onProgressChange` updating).

The `userOffRoute` method is also being called when I make the user go off route. 
The `onAlertLevelChange` is called.

`onRunning` is not being called. 

I have had a few toast messages appear 'DEPART' and 'MEDIUM' and 'HIGH'

I am getting the following in the logs:
```
W/Position: Latitude value seems to be out of range (found: Infinity, expected: [-90, 90]). Did you accidentally reverse the longitude/latitude order?
W/Position: Longitude value seems to be out of range (found: Infinity, expected: [-180, 180]). Did you accidentally reverse the longitude/latitude order?
```
I have had those errors before related to issue #353 but that does not seem to be the problem here.

I am also getting a leaked service connection from the `startNavigation` call, this seemed to be fixed by calling the onStop method (also not in the documentation).
```
    @Override
    protected void onStop() {
        super.onStop();
        mapView.onStop();
        navigationService.onStop();
    }
```
```
Activity ....NavigationActivity has leaked ServiceConnection com.mapbox.services.android.navigation.v5.MapboxNavigation$NavigationServiceConnection@1432b84a that was originally bound here
                                                                           android.app.ServiceConnectionLeaked: Activity ....NavigationActivity has leaked ServiceConnection com.mapbox.services.android.navigation.v5.MapboxNavigation$NavigationServiceConnection@1432b84a that was originally bound here
                                                                               at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1183)
                                                                               at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1077)
                                                                               at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1880)
                                                                               at android.app.ContextImpl.bindService(ContextImpl.java:1863)
                                                                               at android.content.ContextWrapper.bindService(ContextWrapper.java:538)
                                                                               at com.mapbox.services.android.navigation.v5.MapboxNavigation.startNavigation(MapboxNavigation.java:187)
                                                                               at com.ibm.events.android.pb.ui.NavigationActivity$8.onResponse(NavigationActivity.java:387)
                                                                               at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
                                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:155)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5696)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
``` 
 
Shoutout to David Fernández from coedia who has been struggling with the same issue and told me about the startNavigation call (he is also experiencing the same issues above).

**Comment by KatieBarnett** [comment]
Found the `endNavigation()` method which does stop the listener callbacks.

**Comment by KatieBarnett** [comment]
I also randomly get this exception:
```
FATAL EXCEPTION: LocationUpdatedThread
                                                                           Process: com.ibm.events.android.pb, PID: 10803
                                                                           java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.mapbox.services.api.directions.v5.models.DirectionsRoute.getLegs()' on a null object reference
                                                                               at com.mapbox.services.android.navigation.v5.LocationUpdatedThread.handleRequest(LocationUpdatedThread.java:79)
                                                                               at com.mapbox.services.android.navigation.v5.LocationUpdatedThread.access$500(LocationUpdatedThread.java:32)
                                                                               at com.mapbox.services.android.navigation.v5.LocationUpdatedThread$RequestHandler.handleMessage(LocationUpdatedThread.java:334)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:155)
                                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
```
I haven't found a reproducible cause yet.

**Comment by Naroh091** [comment]
As @KatieBarnett said we're experiencing some of this issues too. Thanks to her the leaks are fixed, but some of the methods like `distanceRemainingOnRoute()`, `getDistanceTraveledOnRoute()` and  `getUserSnapToStepDistanceFromManeuver()` are always returning 0.0 even when the steps are changing as they should and `distanceRemainingOnStep()` is decreasing as expected. 

The messages about the reversed longitude/latitude are flowing through our logs too, but for now we didn't notice any issues related to this.

**Comment by cammace** [comment]
The fix for the longitude/latitude log issue is fixed in https://github.com/mapbox/mapbox-java/pull/416. We were making use of `Double.POSITIVE_INFINITY` which our Position check didn't like. 

For the RouteProgress, I have made significant changed to it (see PR https://github.com/mapbox/mapbox-java/pull/415), making it immutable, creating a better structure that matches the iOS routeProgress object, and added test to check many of the issues you guys are experiencing above. The List exception is now fixed, there was a case when the routeleg was null and we were trying to perform calculations on it.

I have included an [example inside our testapp](https://github.com/mapbox/mapbox-java/blob/master/mapbox/app/src/main/java/com/mapbox/services/android/testapp/nav/NavigationActivity.java) which shows how to setup and initialize a navigation session, I strongly encourage having a look. You'll need to use the SNAPSHOT version of mapbox-java in order to see these changes (once the PRs are merged into master). As noted above, since the RouteProgress object has changed so much, chances are your code will break (though it should be rather easy to fix). 

As for the original issue in this ticket, the event listener is now working properly, closing but if you guys have any other issues or questions, feel free to open a new issue.

**Comment by KatieBarnett** [comment]
I will give it a try. Thanks for your help.

**Comment by Vahn84** [comment]
Hi @cammace 

I'm working on the 0.3.0 (but this is happening on 0.3.1 too), as reported on the readme, but i'm still having that bad bug as @KatieBarnett  had. You said  "The List exception is now fixed", tried to update at the 0.4.0 snapshot but it broke my code and i had to turn back

this is the error log for the 0.3.0
`  java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.mapbox.services.api.directions.v5.models.DirectionsRoute.getLegs()' on a null object reference
                                                                                     at com.mapbox.services.android.navigation.v5.RouteProgress.getCurrentLeg(RouteProgress.java:98)
                                                                                     at com.mapbox.services.android.navigation.v5.RouteProgress.<init>(RouteProgress.java:58)
                                                                                     at com.mapbox.services.android.navigation.v5.NavigationEngine.onLocationChanged(NavigationEngine.java:63)
                                                                                     at com.mapbox.services.android.navigation.v5.NavigationService.onLocationChanged(NavigationService.java:228)
                                                                                     at com.mapbox.services.android.location.LostLocationEngine.onLocationChanged(LostLocationEngine.java:130)
                                                                                     at com.mapzen.android.lost.internal.LostClientManager$1.notify(LostClientManager.java:155)
                                                                                     at com.mapzen.android.lost.internal.LostClientManager$1.notify(LostClientManager.java:153)
                                                                                     at com.mapzen.android.lost.internal.LostClientManager.iterateAndNotify(LostClientManager.java:308)
                                                                                     at com.mapzen.android.lost.internal.LostClientManager.reportLocationChanged(LostClientManager.java:152)
                                                                                     at com.mapzen.android.lost.internal.FusedLocationProviderServiceImpl.reportLocation(FusedLocationProviderServiceImpl.java:126)
                                                                                     at com.mapzen.android.lost.internal.FusionEngine.onLocationChanged(FusionEngine.java:191)
                                                                                     at com.mapzen.android.lost.internal.FusionEngine.checkLastKnownAndNotify(FusionEngine.java:183)
                                                                                     at com.mapzen.android.lost.internal.FusionEngine.checkLastKnownGps(FusionEngine.java:169)
                                                                                     at com.mapzen.android.lost.internal.FusionEngine.enable(FusionEngine.java:119)
                                                                                     at com.mapzen.android.lost.internal.LocationEngine.setRequest(LocationEngine.java:45)
                                                                                     at com.mapzen.android.lost.internal.FusedLocationProviderServiceImpl.requestLocationUpdates(FusedLocationProviderServiceImpl.java:60)
                                                                                     at com.mapzen.android.lost.internal.FusedLocationProviderService.requestLocationUpdates(FusedLocationProviderService.java:69)
                                                                                     at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.requestLocationUpdates(FusedLocationProviderApiImpl.java:109)
                                                                                     at com.mapbox.services.android.location.LostLocationEngine.requestLocationUpdates(LostLocationEngine.java:116)
                                                                                     at com.mapbox.services.android.navigation.v5.NavigationService.onConnected(NavigationService.java:221)
                                                                                     at com.mapbox.services.android.location.LostLocationEngine.onConnected(LostLocationEngine.java:69)
                                                                                     at com.mapzen.android.lost.internal.LostApiClientImpl.connect(LostApiClientImpl.java:39)
                                                                                     at com.mapbox.services.android.location.LostLocationEngine.activate(LostLocationEngine.java:50)
                                                                                     at com.mapbox.services.android.navigation.v5.NavigationService.startRoute(NavigationService.java:146)
                                                                                     at com.mapbox.services.android.navigation.v5.MapboxNavigation$NavigationServiceConnection.onServiceConnected(MapboxNavigation.java:459)
                                                                                     at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1223)
                                                                                     at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1240)
                                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

In 0.3.1 it happens the same but on RouteProgress.create function

Can you help me please?

**Comment by cammace** [comment]
I haven't run into this issue in a while. Can you try updating to the 0.4.0-SNAPSHOT which contains many fixes? If the issue still occurs, could you open a ticket in [mapbox-navigation-android](github.com/mapbox/mapbox-navigation-android).

**Comment by Vahn84** [comment]
Hi @cammace sorry for the late response

I had to do some changes on my side, before updating the sdk to the beta version. It seems that the beta sdk has got rid of any nullpointer exception fired before during onProgressChange.

But there are still a bunch of issues:

1) eventi listener for userOffRoute never fires
2) AlertLevelChangeListener has been removed from the sdk, or renamed...and I can't find a way to implement it back
